### ISSUE TITLE
Xml/Report FromXml does not provide an overload for additional parameters.

### ISSUE THREAD

**Issue by bigsmity** [dgm9704/Xoxo#84]
public static Report FromXml(string content)
        {
            using (var stream = new MemoryStream())
            using (var writer = new StreamWriter(stream))
            {
                writer.Write(content);
                writer.Flush();

                stream.Position = 0;

                return FromStream(stream);
            }
        }

My workaround was to prepare a stream and use:
public static Report FromStream(Stream stream, bool removeUnusedObjects, bool collapseDuplicateContexts, bool removeDuplicateFacts)

**Comment by dgm9704** [comment]
Thanks for reporting and providing a workaround! I will check this out and get back to you.

**Comment by dgm9704** [comment]
This seems like an easy fix with just adding some overloads. In the meantime, might I ask a about your use case for this? I think originally made the FromXml method just for internal testing purposes and didn't think there would be any actual use for it in an actual application. I'm just curious plus I wan't to make sure I'm not overlooking something else that people actually need.

**Comment by dgm9704** [comment]
fixed in v3.2.1

**Comment by dgm9704** [comment]
Fixed in v3.2.1

**Comment by bigsmity** [comment]
> This seems like an easy fix with just adding some overloads. In the meantime, might I ask a about your use case for this? I think originally made the FromXml method just for internal testing purposes and didn't think there would be any actual use for it in an actual application. I'm just curious plus I wan't to make sure I'm not overlooking something else that people actually need.

Thank you for taking a look at my issues so quickly. We are communicating with a webservice that uses xbrl payloads and are storing responses in a table as a cache to limit these calls. We also anonymize the data and run in future test cases. Using sql server with text column and entity framework, so we have a string which the method suited perfectly.

We just moved up to the current version as we have updated to .net 8 and some new test cases identified the duplicate issue, and then the need to switch off the duplicate parameter.
